font_family      JetBrainsMonoNL Nerd Font Mono
background       #1c0e00
foreground       #e7aa5a
cursor           #bd4924
cursor_text_color #e7aa5a
selection_background #f4cc5d
selection_foreground #1c0e00
color0 #3c260e
color1 #fd6883
color2 #df782d
color3 #f9cc6c
color4 #a87c54
color5 #d77f6b
color6 #bd4924
color7 #e7aa5a
color8 #948a8b
color9 #ff8297
color10 #c8e292
color11 #fcd675
color12 #f8a788
color13 #eb8a75
color14 #dda36e
color15 #f1e5e7
