[colors.primary]
background = "#182538"
foreground = "#eff3f8"
[colors.cursor]
cursor = "#61a7d6"
text = "#182538"
[colors.selection]
background = "#49586d"
text = "#eff3f8"
[colors.normal]
black = "#3a4556"
red = "#437394"
green = "#61a7d6"
yellow = "#76bbee"
blue = "#8da1c8"
magenta = "#b1bfd9"
cyan = "#5693C4"
white = "#B2C5D9"
[colors.bright]
black = "#49586d"
red = "#6868e6"
green = "#add8f5"
yellow = "#b3d5ef"
blue = "#5656bd"
magenta = "#5656bd"
cyan = "#97bfdf"
white = "#eff3f8"
