font_family      JetBrainsMonoNL Nerd Font Mono
background       #182538
foreground       #eff3f8
cursor           #61a7d6
cursor_text_color #182538
selection_background #49586d
selection_foreground #eff3f8
color0 #3a4556
color1 #437394
color2 #61a7d6
color3 #76bbee
color4 #8da1c8
color5 #b1bfd9
color6 #5693C4
color7 #B2C5D9
color8 #49586d
color9 #6868e6
color10 #add8f5
color11 #b3d5ef
color12 #5656bd
color13 #5656bd
color14 #97bfdf
color15 #eff3f8
