-- generated by theme-pack from the active omacosy theme
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.background = "dark"
vim.o.termguicolors = true
vim.g.colors_name = "omacosy"
vim.g.terminal_color_0 = "#3a4556"
vim.g.terminal_color_1 = "#437394"
vim.g.terminal_color_2 = "#61a7d6"
vim.g.terminal_color_3 = "#76bbee"
vim.g.terminal_color_4 = "#8da1c8"
vim.g.terminal_color_5 = "#b1bfd9"
vim.g.terminal_color_6 = "#5693C4"
vim.g.terminal_color_7 = "#B2C5D9"
vim.g.terminal_color_8 = "#49586d"
vim.g.terminal_color_9 = "#6868e6"
vim.g.terminal_color_10 = "#add8f5"
vim.g.terminal_color_11 = "#b3d5ef"
vim.g.terminal_color_12 = "#5656bd"
vim.g.terminal_color_13 = "#5656bd"
vim.g.terminal_color_14 = "#97bfdf"
vim.g.terminal_color_15 = "#eff3f8"
vim.api.nvim_set_hl(0, "Normal", { fg = "#eff3f8", bg = "#182538" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#eff3f8", bg = "#233951" })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#61a7d6", bg = "#233951" })
vim.api.nvim_set_hl(0, "Cursor", { fg = "#182538", bg = "#61a7d6" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#1f3247" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#61a7d6", bold = true })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#49586d" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#365b7a" })
vim.api.nvim_set_hl(0, "Search", { fg = "#182538", bg = "#8da1c8" })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "#182538", bg = "#a7d0ec" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#596b85", italic = true })
vim.api.nvim_set_hl(0, "Constant", { fg = "#5693C4" })
vim.api.nvim_set_hl(0, "String", { fg = "#a7d0ec" })
vim.api.nvim_set_hl(0, "Character", { fg = "#a7d0ec" })
vim.api.nvim_set_hl(0, "Number", { fg = "#6cabda" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#6cabda" })
vim.api.nvim_set_hl(0, "Float", { fg = "#6cabda" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#eff3f8" })
vim.api.nvim_set_hl(0, "Function", { fg = "#61a7d6" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#8da1c8" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#8da1c8" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#8da1c8" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#8da1c8" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#B2C5D9" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#61a7d6" })
vim.api.nvim_set_hl(0, "Type", { fg = "#B2C5D9" })
vim.api.nvim_set_hl(0, "Special", { fg = "#a7d0ec" })
vim.api.nvim_set_hl(0, "Todo", { fg = "#182538", bg = "#61a7d6", bold = true })
vim.api.nvim_set_hl(0, "Title", { fg = "#61a7d6", bold = true })
vim.api.nvim_set_hl(0, "Directory", { fg = "#61a7d6" })
vim.api.nvim_set_hl(0, "MatchParen", { fg = "#61a7d6", bold = true })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#eff3f8", bg = "#233951" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#596b85", bg = "#1f3247" })
vim.api.nvim_set_hl(0, "TabLine", { fg = "#596b85", bg = "#1f3247" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#182538", bg = "#61a7d6" })
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#eff3f8", bg = "#233951" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#182538", bg = "#61a7d6" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#49586d" })
vim.api.nvim_set_hl(0, "VertSplit", { fg = "#49586d" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#8da1c8" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#6cabda" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#61a7d6" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#B2C5D9" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#8da1c8", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#6cabda", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#61a7d6", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#B2C5D9", undercurl = true })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#a7d0ec" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#61a7d6" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#8da1c8" })
vim.api.nvim_set_hl(0, "@comment", { link = "Comment" })
vim.api.nvim_set_hl(0, "@string", { link = "String" })
vim.api.nvim_set_hl(0, "@number", { link = "Number" })
vim.api.nvim_set_hl(0, "@boolean", { link = "Boolean" })
vim.api.nvim_set_hl(0, "@function", { link = "Function" })
vim.api.nvim_set_hl(0, "@function.call", { link = "Function" })
vim.api.nvim_set_hl(0, "@keyword", { link = "Keyword" })
vim.api.nvim_set_hl(0, "@type", { link = "Type" })
vim.api.nvim_set_hl(0, "@variable", { link = "Identifier" })
vim.api.nvim_set_hl(0, "@constant", { link = "Constant" })
vim.api.nvim_set_hl(0, "@operator", { link = "Operator" })
vim.o.cursorline = true
vim.o.number = true
vim.o.signcolumn = 'yes'
vim.o.laststatus = 3
vim.o.smoothscroll = true
vim.o.fillchars = "eob: ,vert:│,horiz:─"
vim.o.statusline = "%#TabLineSel# %t %m %#StatusLine#%= %Y  %l:%c "

vim.o.guicursor = "n-v-c:ver30-Cursor,i-ci-ve:ver30-Cursor,r-cr:hor20-Cursor"
if _G.omacosy_cursor and _G.omacosy_cursor.timer then
  pcall(function()
    _G.omacosy_cursor.timer:stop()
    _G.omacosy_cursor.timer:close()
  end)
end
_G.omacosy_cursor = { token = 0 }
local shades = { "#61a7d6", "#a7d0ec", "#61a7d6" }
local linebg = "#1f3247"
local cursorfg = "#182538"
local kind = "glide"
local group = vim.api.nvim_create_augroup("omacosy-cursor", { clear = true })
if kind == "pulse" then
  local i = 0
  local timer = vim.uv.new_timer()
  _G.omacosy_cursor.timer = timer
  timer:start(0, 680, vim.schedule_wrap(function()
    i = (i % #shades) + 1
    vim.api.nvim_set_hl(0, "Cursor", { fg = cursorfg, bg = shades[i] })
  end))
elseif kind == "trail" then
  local ns = vim.api.nvim_create_namespace("omacosy-cursor")
  local marks = {}
  vim.api.nvim_set_hl(0, "OmacosyTrail1", { fg = shades[1], bold = true })
  vim.api.nvim_set_hl(0, "OmacosyTrail2", { fg = shades[2] })
  vim.api.nvim_set_hl(0, "OmacosyTrail3", { fg = shades[3] })
  vim.api.nvim_create_autocmd("CursorMoved", {
    group = group,
    callback = function()
      local buf = vim.api.nvim_get_current_buf()
      local pos = vim.api.nvim_win_get_cursor(0)
      table.insert(marks, 1, { buf, pos[1] - 1, pos[2] })
      while #marks > 3 do table.remove(marks) end
      vim.api.nvim_buf_clear_namespace(buf, ns, 0, -1)
      for n, mark in ipairs(marks) do
        if mark[1] == buf and mark[3] >= 0 then
          pcall(vim.api.nvim_buf_set_extmark, buf, ns, mark[2], mark[3], {
            end_col = mark[3] + 1,
            hl_group = "OmacosyTrail" .. n,
          })
        end
      end
    end,
  })
elseif kind == "beacon" then
  local last = { 1, 0 }
  vim.api.nvim_create_autocmd("CursorMoved", {
    group = group,
    callback = function()
      local pos = vim.api.nvim_win_get_cursor(0)
      local jump = math.abs(pos[1] - last[1]) + math.abs(pos[2] - last[2])
      last = { pos[1], pos[2] }
      if jump < 6 then return end
      local id = vim.fn.matchaddpos("IncSearch", { { pos[1], math.max(pos[2], 0) + 1, 2 } })
      vim.defer_fn(function() pcall(vim.fn.matchdelete, id) end, 160)
    end,
  })
else
  vim.api.nvim_create_autocmd("CursorMoved", {
    group = group,
    callback = function()
      _G.omacosy_cursor.token = _G.omacosy_cursor.token + 1
      local token = _G.omacosy_cursor.token
      local bg = linebg
      for step, blend in ipairs({ 50, 28, 10, 0 }) do
        vim.defer_fn(function()
          if token ~= _G.omacosy_cursor.token then return end
          vim.api.nvim_set_hl(0, "CursorLine", { bg = bg, blend = blend })
        end, step * 36)
      end
    end,
  })
end
