[colors.primary]
background = "#131610"
foreground = "#93B298"
[colors.cursor]
cursor = "#7BAE4E"
text = "#131610"
[colors.selection]
background = "#7BAE4E"
text = "#0E150F"
[colors.normal]
black = "#272e25"
red = "#44b83a"
green = "#7BAE4E"
yellow = "#A8BE5A"
blue = "#4a945e"
magenta = "#4CAF7E"
cyan = "#7CBCA0"
white = "#93B298"
[colors.bright]
black = "#33482F"
red = "#44b83a"
green = "#7BAE4E"
yellow = "#A8BE5A"
blue = "#4a945e"
magenta = "#4CAF7E"
cyan = "#7CBCA0"
white = "#A8C6AE"
