font-family = JetBrainsMonoNL Nerd Font Mono
font-family = JetBrainsMono Nerd Font Mono
font-size = 14
background = 131610
foreground = 93B298
cursor-color = 517a39
cursor-text = 131610
selection-background = 6a8e45
selection-foreground = 0E150F
macos-icon = custom-style
macos-icon-ghost-color = 517a39
macos-icon-screen-color = 131610
palette = 0=#0B0E09
palette = 1=#E5484D
palette = 2=#7BAE4E
palette = 3=#A8BE5A
palette = 4=#5B8CA8
palette = 5=#4CAF7E
palette = 6=#7CBCA0
palette = 7=#93B298
palette = 8=#33482F
palette = 9=#E5484D
palette = 10=#7BAE4E
palette = 11=#A8BE5A
palette = 12=#5B8CA8
palette = 13=#4CAF7E
palette = 14=#7CBCA0
palette = 15=#A8C6AE
