font_family      JetBrainsMonoNL Nerd Font Mono
background       #131610
foreground       #93B298
cursor           #7BAE4E
cursor_text_color #131610
selection_background #7BAE4E
selection_foreground #0E150F
color0 #272e25
color1 #44b83a
color2 #7BAE4E
color3 #A8BE5A
color4 #4a945e
color5 #4CAF7E
color6 #7CBCA0
color7 #93B298
color8 #33482F
color9 #44b83a
color10 #7BAE4E
color11 #A8BE5A
color12 #4a945e
color13 #4CAF7E
color14 #7CBCA0
color15 #A8C6AE
