font_family      JetBrainsMonoNL Nerd Font Mono
background       #131610
foreground       #93B298
cursor           #A8C6AE
selection_background #668b42
selection_foreground #0E150F
color0 #0B0E09
color1 #E5484D
color2 #7BAE4E
color3 #A8BE5A
color4 #5B8CA8
color5 #4CAF7E
color6 #7CBCA0
color7 #93B298
color8 #33482F
color9 #E5484D
color10 #7BAE4E
color11 #A8BE5A
color12 #5B8CA8
color13 #4CAF7E
color14 #7CBCA0
color15 #A8C6AE
